on:
  push:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day
env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  PASSWORD: ${{ secrets.PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const delay = ms => new Promise(res => setTimeout(res, ms));
            
            github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
              
            while (true) {
              core.info('Waiting for workflow to cancel ...');
              await delay(5000);
            }
            
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          cache: 'pip' # caching pip dependencies
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py
