name: Python Script Execution

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      # Debug: Check pip cache directory
      - name: Check pip cache directory
        run: pip cache dir

      # Caching pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Debug: Show hash for requirements.txt
      - name: Show hash for requirements.txt
        run: echo ${{ hashFiles('requirements.txt') }}
      
      # Install Python packages
      - name: Install Python packages
        run: pip install -r requirements.txt

      # Debug: List cache directory contents
      - name: List cache directory contents
        run: ls -al ~/.cache/pip

      - name: Execute Python script
        run: python main.py