on:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (exactly at limit)
env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          cache: 'pip' # caching pip dependencies
          
      - name: cache python packages
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py
