name: Python Script Execution

on:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
          echo "Pip cache directory: $(pip cache dir)"

      - name: Generate requirements hash
        id: req-hash
        run: |
          echo "hash=$(md5sum requirements.txt | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "Requirements hash: $(md5sum requirements.txt | awk '{print $1}')"

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-step
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ steps.req-hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache hit/miss info
        run: |
          if ${{ steps.cache-step.outputs.cache-hit == 'true' }}; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi

      - name: Install dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List installed packages
        run: pip list

      - name: Execute Python script
        run: python main.py
