name: Python Script Execution

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Execute Python script
        run: python main.py