name: 03 - Python Script Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install -r /requiremtns.txt
      - name: Execute Python script # Run the run.py to get the latest data
        run: python run.py
